### ISSUE TITLE
LGR Survival

### ISSUE THREAD

**Issue by mackerman44** [mackerman44/telemetyr#13]
At some point, we should consider adding the data and functionality to estimate and compare survival to LGR. Start by adding PIT tag lists for all releases at LLRTP with perhaps date, season, etc. to compare survival between RT and PIT fish by year and overall.

Can we leverage PTAGIS queries via R? Do analysis in TribPit or do ourselves? Questions to ponder...

**Comment by KevinSee** [comment]
Completed a CJS model with both PIT tagged and RT tagged fish, including a parameter to estimate differential survival in each reach between those two groups.
