### ISSUE TITLE
Survival models

### ISSUE THREAD

**Issue by KevinSee** [mackerman44/telemetyr#17]
Things to look into:

- Simple CJS model using batch_1 tags and RT detections only

- Bring in detections from batch_2 and batch_3 tags, starting them in the reach with their first detection. 

- Kaplan-Meier known-fates model

- CJS models for right censored data (when batteries die)

Other ideas?

**Comment by KevinSee** [comment]
Completed CJS models using:

* PIT tag observations only. 
* RT observations only, including bringing in batch 2 and batch 3 tags, based on first observation of them (batch 2/3 tags that are never detected are not included in the model. Does this bias results?)

**Comment by KevinSee** [comment]
Note that Kaplan-Meier and other known-fate models usually have data about when (or where) at least some individuals die. Right censored data in that context are individuals that have survived up to some point and then no further data is collected (e.g. the study ends, the radio tag dies). With this study, such models are probably not appropriate, since we never **know** when a fish actually dies, we just stop detecting it.

**Comment by mackerman44** [comment]
Transferred to BiomarkABS/telemetyr
