### ISSUE TITLE
Fix season_start and season_end argument formats in summarise_timer_data()

### ISSUE THREAD

**Issue by mackerman44** [mackerman44/telemetyr#2]
I need to fix the formatting of the season_start and season_end arguments within the summarise_timer_data(). When they are used in the hr_range object, they are assigned an hour based on an unknown tz (I think)

**Comment by KevinSee** [comment]
I modified the code slightly, to match how I would have done it. Not sure if it exactly fixed the issue you're talking about, but I think it works. If season_start and season_end are left NULL, then hr_range adopts the time zone from the compress_df, which is the local time zone of the machine that compressed that data (I believe). If you set those values, then the time zone will be the same as the machine that's running that function at the moment (I think). 

However, I don't think the function will translate one time zone to another, so it may not really matter at all. For instance, I can run that on my machine, and don't see any issues, and presumably you can run it on yours. Maybe we should both run it at the same time, on the same dataset, with a set "season_start" and "season_end", and see if we can find any differences in the proportion of time receivers are operational.

**Comment by mackerman44** [comment]
Cool! I like those modifications. I knew a function in lubridate would make that much easier. I really need to go through a lubridate tutorial, sometime.

Quick question, wouldn't "YYYYMMDD" format be equivalent to "%Y%0m%0d" (in lubridate vernacular)? Although I like how you used "YYYYMMDD" in documentation, more intuitive for the layperson.

I forgot about the above issue, I was mostly concerned with keep dates in my functions similar in format to the dates in your arguments, functions. But I'm interested in exploring the above.....sometime....
