### ISSUE TITLE
Smolt vs Presmolt Life-History Comparison

### ISSUE THREAD

**Issue by mackerman44** [mackerman44/telemetyr#23]
I'd like to do a comparison of the smolt (NRR) vs. presmolt (DSR) life histories in the Lemhi. This would include:

1. Estimate emigrant abundance at LLTRP by brood year and life stage, likely going back to the BY where Braden/Mike H. think abundance estimates are legit (BY2013?).
2. Estimate survival to LGR by brood year and life stage going back to start of LLTRP.
2a. As part of the above, we could also do the all PIT presmolts vs. radio AND PIT presmolts starting with BY2017 to estimate tag burden.
3. LGR SAR by brood year and life stage.
4. Lemhi adult abundance parsed by BY and life stage. Would this allow for an overall Lemhi SAR by brood year and life stage?

This doesn't necessarily need to be available for annual reports, but I'd like to compile for manuscript 1.

**Comment by KevinSee** [comment]
The PIT tag only CJS model code is ready to go. Just need to compile tag lists for presmolts/smolts released from LLTRP every year as far back as possible

**Comment by mackerman44** [comment]
Transferred this issue to KevinSee/LemhiRT
