### ISSUE TITLE
Missing packages while installing

### ISSUE THREAD

**Issue by port5518** [mackerman44/telemetyr#32]
Hey Guys,
The following packages are missing upon installation. (vctrs, lifecycle, viridis, janitor)

Also I am still unable to load the telemetyr package here is the errors

________________________________________________________________________________________________________

> devtools::install_github("mackerman44/telemetyr",build_vignettes = TRUE)
Downloading GitHub repo mackerman44/telemetyr@master
Skipping 5 packages not available: dplyr, lubridate, purrr, readr, stringr
√  checking for file 'C:\Users\porterni\AppData\Local\Temp\RtmpMXuKHI\remotes414496b3f1b\mackerman44-telemetyr-896e388/DESCRIPTION' (1.1s)
-  preparing 'telemetyr': (2.5s)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes (538ms)
E  creating vignettes (1m 45.2s)
   --- re-building 'CJS.Rmd' using rmarkdown
   Warning: replacing previous import 'dplyr::intersect' by 'lubridate::intersect' when loading 'telemetyr'
   Warning: replacing previous import 'dplyr::union' by 'lubridate::union' when loading 'telemetyr'
   Warning: replacing previous import 'dplyr::setdiff' by 'lubridate::setdiff' when loading 'telemetyr'
   Warning: replacing previous import 'magrittr::set_names' by 'purrr::set_names' when loading 'telemetyr'
   Warning: replacing previous import 'magrittr::extract' by 'tidyr::extract' when loading 'telemetyr'
   -- Attaching packages ----------------------------------------------------------------------------------------------------------- tidyverse 1.3.0 --
   v ggplot2 3.3.0     v purrr   0.3.3
   v tibble  2.1.3     v dplyr   0.8.5
   v tidyr   1.0.2     v stringr 1.4.0
   v readr   1.3.1     v forcats 0.5.0
   -- Conflicts -------------------------------------------------------------------------------------------------------------- tidyverse_conflicts() --
   x dplyr::filter() masks stats::filter()
   x dplyr::lag()    masks stats::lag()
   
   Attaching package: 'lubridate'
   
   The following object is masked from 'package:base':
   
       date
   
   
   Attaching package: 'magrittr'
   
   The following object is masked from 'package:purrr':
   
       set_names
   
   The following object is masked from 'package:tidyr':
   
       extract
   
   
   Attaching package: 'janitor'
   
   The following objects are masked from 'package:stats':
   
       chisq.test, fisher.test
   
   Quitting from lines 25-35 (CJS.Rmd) 
   Error: processing vignette 'CJS.Rmd' failed with diagnostics:
   there is no package called 'rjags'
   --- failed re-building 'CJS.Rmd'
   
   --- re-building 'Data_Prep.Rmd' using rmarkdown
   Joining, by = "tag_id"
   Warning: Column `site` joining character vector and factor, coercing into character vector
   Warning: Column `receiver` joining character vector and factor, coercing into character vector
   Joining, by = c("site", "receiver", "valid", "tag_id", "start", "end", "n", "week")
   --- finished re-building 'Data_Prep.Rmd'
   
   --- re-building 'Diagnostics.Rmd' using rmarkdown
   Joining, by = c("receiver", "hr")
   Joining, by = "receiver"
   Joining, by = "receiver"
   Joining, by = c("receiver", "hr")
   Joining, by = "receiver"
   Joining, by = "receiver"
   Joining, by = c("receiver", "hr")
   Joining, by = "receiver"
   Joining, by = "receiver"
   Joining, by = "receiver"
   Warning: Column `receiver` joining character vector and factor, coercing into character vector
   Joining, by = "tag_id"
   Joining, by = "duty_cycle"
   Warning: Removed 9 row(s) containing missing values (geom_path).
   --- finished re-building 'Diagnostics.Rmd'
   
   SUMMARY: processing the following file failed:
     'CJS.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'telemetyr' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Joining, by = "tag_id"
E> Joining, by = "duty_cycle"
E> Warning: Removed 9 row(s) containing missing values (geom_path).
E> --- finished re-building 'Diagnostics.Rmd'
E> 
E> SUMMARY: processing the following file failed:
E>   'CJS.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted

**Comment by KevinSee** [comment]
Nick, I just updated the DESCRIPTION file with some of the packages mentioned, which hopefully means they get downloaded automatically when you install telemetyr now. 

To build the CJS vignette, you're going to need the JAGS software. You can download it here:

https://sourceforge.net/projects/mcmc-jags/files/

Be sure to grab version 4.0 or greater. And then you'll want to install the "rjags" package from CRAN (`install.packages("rjags")` )

After you do those 2 things, try installing telemetyr again.

**Comment by port5518** [comment]
Thanks Kevin these are the packages I have had to install so far. 

install.packages("vctrs")
install.packages("lifecycle")
install.packages("viridis")
install.packages("janitor")
install.packages("rjags")
install.packages("maggrittr")
