### ISSUE TITLE
post_pack not included

### ISSUE THREAD

**Issue by port5518** [mackerman44/telemetyr#37]
Hey guys,
The package post_pack by bstaton1 is not included in the package currently and I had to load it from GitHub. 

devtools::install_github("bstaton1/postpack")

**Comment by KevinSee** [comment]
I added something to the DESCRIPTION file that will hopefully fix this. It was based on this exchange: 
https://stackoverflow.com/questions/30493388/create-an-r-package-that-depends-on-another-r-package-located-on-github

**Comment by mackerman44** [comment]
Good catch. Does it make sense to also add mention of the "postpack" package in the README?

**Comment by port5518** [comment]
This is working correctly now and it loads with telemetyr.
