### ISSUE TITLE
Newest version only has a subset of tag_df

### ISSUE THREAD

**Issue by port5518** [mackerman44/telemetyr#38]
The newest version of telemetyr only has a subset of the tag_df 38 tags in total. Can we include the full dataset?

**Comment by KevinSee** [comment]
The tag_df included in the R package is a subset of the 18-19 data, and was kept small on purpose, so the vignettes build quickly and the included data-sets aren't too big. Nick, if you go to the NAS, and look in Nick/telemetry/raw, you'll see 3 R objects whose names start with "cap_hist". If you load one of those into R, the cap_hist_list will show up, which includes the full tag_df for that year.
