### ISSUE TITLE
summarise_timer_data & summarise_noise_data

### ISSUE THREAD

**Issue by port5518** [mackerman44/telemetyr#39]
In both of these functions, the levels defined in the tmp file should be receiver_codes not receiver_nms. This will allow the user to define the order of the sites using the receiver_codes argument in the function. 

e.g.
Current    
tmp = tmp %>% mutate(receiver = factor(receiver, levels = receiver_nms))
Desired
tmp = tmp %>% mutate(receiver = factor(receiver, levels = receiver_codes))

**Comment by KevinSee** [comment]
I fixed a line of code so it now accepts use defined order of receiver codes in both functions. Nick reports that it nows works as expected.
