### ISSUE TITLE
Survival Models

### ISSUE THREAD

**Issue by mackerman44** [mackerman44/telemetyr#4]
Some of this could perhaps, at some point, be moved to KevinSee/LemhiRT.

From @KevinSee :
On April 22, 2020 - 
Things to look into:

Simple CJS model using batch_1 tags and RT detections only

Bring in detections from batch_2 and batch_3 tags, starting them in the reach with their first detection.

Kaplan-Meier known-fates model

CJS models for right censored data (when batteries die)

Other ideas?

On May 5, 2020 -
Completed CJS models using:

PIT tag observations only.
RT observations only, including bringing in batch 2 and batch 3 tags, based on first observation of them (batch 2/3 tags that are never detected are not included in the model. Does this bias results?)

On May 29, 2020 -
Note that Kaplan-Meier and other known-fate models usually have data about when (or where) at least some individuals die. Right censored data in that context are individuals that have survived up to some point and then no further data is collected (e.g. the study ends, the radio tag dies). With this study, such models are probably not appropriate, since we never know when a fish actually dies, we just stop detecting it.

**Comment by KevinSee** [comment]
Given that we have completed the first 2 models in this list, and I believe determined that the last 2 are inappropriate, since we never know when fish actually die, or when the batteries actually stop working, I'm going to close this issue. We might revisit it in the KevinSee/LemhiRT project at some point.
