### ISSUE TITLE
Fix tag metadata for 2019-20

### ISSUE THREAD

**Issue by KevinSee** [mackerman44/telemetyr#40]
Nick corrected the release time for 2019-20 tags (there was an issue with which time zone the original data was in versus the detection data). The updated times are in the file on the NAS, _data/telemetry/lemhi/tag_release/TagReleases2019_2020.csv_. The overall metadata contained in the file _lemhi_winter_telemetry_tag_info.xlsx_ in the same folder needs to be updated, and then the 19-20 csv file can be deleted.

The other issue with the xlsx file is there are 3 tags that appear twice in the 19-20 season:

- 3320C
- 3340C
- 9190C

The duplicated tags don't have the same data though; different lengths, weights, release times and even duty cycle (for 9190C). The first record of each (by release time) matches the data in TagReleases2019_2020.csv. We need to confirm which data is correct, and delete the rows that are incorrect.

**Comment by mackerman44** [comment]
I updated the release times for 19/20 releases in _lemhi_winter_telemetry_tag_info.xlsx_ to match those in _data/telemetry/lemhi/tag_release/TagReleases2019_2020.csv_ I also removed the three records for:

- 3320C
- 3340C
- 9190C

That do not appear in Nick's release data, assuming that that file contains the most QA/QC'd release records. And deleted the _TagReleases2019_2020.csv_ file from that directory.
