### ISSUE TITLE
rjags

### ISSUE THREAD

**Issue by mackerman44** [mackerman44/telemetyr#43]
May need to add rjags as an import after Kevin updated CJS vignette. My first attempt at install package failed here.

**Comment by KevinSee** [comment]
There isn't anything in the CJS vignette that requires rjags. There are a couple functions from the postpack package, but that should get installed with telemetyr. Keep me posted about whether the vignette eventually builds or not.

**Comment by KevinSee** [comment]
Sounds like we've got this sorted, and the CJS vignette is building fine.
