### ISSUE TITLE
Read_txt_data error

### ISSUE THREAD

**Issue by ntfuchs1** [mackerman44/telemetyr#45]
I am attempting to run the read_txt_data and clean_raw_data functions within the telemetyr package but get errors stating "cannot allocate vector of size XX." Is there a mb file size limit that this package is unable to work with?

**Comment by KevinSee** [comment]
That is not an error specific to the telemetyr package, that is an issue directly with R. I believe it's specific to the user's computer in that different computers have a different maximum amount of memory that R can utilize. For example, I was able to run the `read_txt_data()` function on files of size up to 244 MB (granted, most of them were in the <1 MB - 10 MB range).

**Comment by ntfuchs1** [comment]
Cool, the compression seems to have worked now that the memory limit has increased, so far so good.

Nate
